// web-ui/src/components/Header.vue
<template>
  <div class="header">
    <div class="header-content">
      <!-- Logo + Brand -->
      <a href="/" class="logo">
        <img src="/logo.png" alt="MyMockupBook" class="logo-img" />
        <span class="brand-name">MyMockupBook</span>
      </a>

      <!-- 中间导航 -->
      <nav class="nav-links">
        <a href="/" class="nav-link">Generator</a>
        <a href="/#how-it-works" class="nav-link">How It Works</a>
        <a href="/#templates" class="nav-link">Templates</a>
        <a href="/#faq" class="nav-link">FAQ</a>
      </nav>

      <!-- 右侧 CTA -->
      <a href="/" class="cta-btn">Create Mockup</a>
    </div>
  </div>
</template>

<script>
export default {
  name: 'Header'
}
</script>

<style scoped>
.header {
  background: white;
  position: sticky;
  top: 0;
  z-index: 100;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.08);
  width: 100%;
}

.header-content {
  width: 100%;
  max-width: 1400px;
  margin: 0 auto;
  padding: 0 2rem;
  display: flex;
  align-items: center;
  justify-content: space-between;
  height: 56px;
  gap: 2rem;
}

.logo {
  display: flex;
  align-items: center;
  gap: 10px;
  text-decoration: none;
  flex-shrink: 0;
}

.logo-img {
  height: 36px;
  width: auto;
  display: block;
}

.brand-name {
  font-size: 1.1rem;
  font-weight: 700;
  color: #111827;
}

.nav-links {
  display: flex;
  align-items: center;
  gap: 28px;
  margin: 0 auto;
}

.nav-link {
  text-decoration: none;
  color: #374151;
  font-weight: 500;
  font-size: 0.9rem;
  transition: color 0.2s;
  white-space: nowrap;
}

.nav-link:hover {
  color: #3b82f6;
}

.cta-btn {
  display: inline-block;
  background: #3b82f6;
  color: white;
  text-decoration: none;
  padding: 8px 18px;
  border-radius: 6px;
  font-weight: 600;
  font-size: 0.88rem;
  transition: background 0.2s;
  flex-shrink: 0;
  white-space: nowrap;
}

.cta-btn:hover {
  background: #2563eb;
}

/* 平板：收起中间导航 */
@media (max-width: 900px) {
  .nav-links {
    display: none;
  }
}

@media (max-width: 768px) {
  .header-content {
    padding: 0 1rem;
    height: 50px;
    gap: 1rem;
  }

  .logo-img {
    height: 30px;
  }

  .brand-name {
    font-size: 0.95rem;
  }

  .cta-btn {
    padding: 6px 12px;
    font-size: 0.82rem;
  }
}
</style>

// nextjs-app/src/components/Header.tsx
"use client";

import Link from "next/link";
import Image from "next/image";

export default function Header() {
  return (
    <header className="bg-white sticky top-0 z-50 shadow-sm w-full">
      <div className="max-w-[1400px] mx-auto px-8 flex items-center justify-between h-14 gap-8">
        {/* Logo + Brand */}
        <Link href="/" className="flex items-center gap-2.5 no-underline flex-shrink-0">
          <Image src="/logo.png" alt="MyMockupBook" width={36} height={36} className="block" />
          <span className="text-[1.1rem] font-bold text-gray-900">MyMockupBook</span>
        </Link>

        {/* 中间导航 */}
        <nav className="hidden lg:flex items-center gap-7 mx-auto">
          <Link href="/" className="no-underline text-gray-700 font-medium text-sm hover:text-blue-500 transition-colors whitespace-nowrap">
            Generator
          </Link>
          <Link href="/#how-it-works" className="no-underline text-gray-700 font-medium text-sm hover:text-blue-500 transition-colors whitespace-nowrap">
            How It Works
          </Link>
          <Link href="/#templates" className="no-underline text-gray-700 font-medium text-sm hover:text-blue-500 transition-colors whitespace-nowrap">
            Templates
          </Link>
          <Link href="/#faq" className="no-underline text-gray-700 font-medium text-sm hover:text-blue-500 transition-colors whitespace-nowrap">
            FAQ
          </Link>
        </nav>

        {/* 右侧 CTA */}
        <Link
          href="/"
          className="inline-block bg-blue-500 text-white no-underline px-[18px] py-2 rounded-md font-semibold text-sm hover:bg-blue-600 transition-colors flex-shrink-0 whitespace-nowrap"
        >
          Create Mockup
        </Link>
      </div>
    </header>
  );
}
